name: sparkui
author: Alexander Adeniyin Ewetumo<trinoxf@gmail.com>
version: 0.0.1
homepage: http://github.com/influx6/sparkui.dart
description: Sparkflow integration with noflo-UI
dependencies:
  browser: any
  ds: any
  guardedfs: any
  hub: any
  path: any
  socketire: any
  sparkflow: any
  streamable: any
